---
extends: airbnb
parser: babel-eslint
env:
  browser: true
  node: true
rules:
  arrow-parens:
  - 2
  - as-needed
  consistent-return: 0
  default-case: 0
  function-paren-newline:
  - 2
  - consistent
  import/first: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/order:
  - 2
  - groups:
    - - builtin
      - external
    - sibling
    - parent
    - index
    newlines-between: always
  import/prefer-default-export: 0
  indent:
  - 2
  - tab
  jsx-a11y/anchor-is-valid:
  - 2
  - components:
    - Link
    specialLink:
    - to
  jsx-a11y/label-has-for: 0
  no-console:
  - 2
  - allow:
    - info
    - error
  no-multiple-empty-lines:
  - 2
  - max: 1
    maxBOF: 0
    maxEOF: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-nested-ternary: 0
  no-shadow:
  - 2
  - allow:
    - err
  no-tabs: 0
  no-underscore-dangle: 0
  object-curly-newline: 0
  react/jsx-filename-extension:
  - 2
  - extensions:
    - .js
  react/jsx-indent:
  - 2
  - tab
  react/jsx-indent-props:
  - 2
  - tab
