---
apiVersion: v1
kind: Namespace
metadata:
  name: colonists

---
apiVersion: v1
kind: Service
metadata:
  namespace: colonists
  name: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 12950

---
apiVersion: v1
kind: Service
metadata:
  namespace: colonists
  name: app
spec:
  selector:
    app: app
  ports:
  - name: http
    port: 80
    targetPort: 12951

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: colonists
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gcr.io/kunkels-core/colonists-api:$SHORT_SHA
        env:
        - name: NODE_ENV
          value: production
        - name: AUTH_GOOGLE_CLIENT_ID
          value: 1043711719111-hseag7asmi65f9qp737ovmcj1sh5vool.apps.googleusercontent.com
        - name: AUTH_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: colonists-secrets
              key: google_client_secret
        - name: AUTH_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: colonists-secrets
              key: token_salt
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: colonists-secrets
              key: mongodb_url
        - name: MONGO_DB
          value: colonists

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: colonists
  name: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/kunkels-core/colonists-app:$SHORT_SHA
        env:
        - name: NODE_ENV
          value: production
        - name: API_URL_SERVER
          value: api
        - name: API_URL
          value: https://api.colonists.io
        - name: APP_URL
          value: https://colonists.io
