version: '3'

services:
  api:
    build:
      context: ./pkg/api
      dockerfile: Dockerfile.dev
    command: yarn watch
    depends_on:
    - babel
    restart: unless-stopped
    ports:
    - 12950:12950
    volumes:
    - .:/code

  app_server:
    build:
      context: .
      dockerfile: ./pkg/app/Dockerfile.dev
    command: yarn watch:server
    depends_on:
    - babel
    restart: unless-stopped
    ports:
    - 12951:12951
    volumes:
    - .:/code

  babel:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn watch:scripts
    volumes:
    - .:/code
