version: '3'

services:
  api:
    build:
      context: ./pkg/api
      dockerfile: Dockerfile.dev
    command: yarn watch
    depends_on:
    - babel
    environment:
      AUTH_GOOGLE_CLIENT_ID: 1043711719111-hseag7asmi65f9qp737ovmcj1sh5vool.apps.googleusercontent.com
      AUTH_GOOGLE_CLIENT_SECRET: Ln_kQg7oM_8y3IEEw82cG3dJ
      AUTH_TOKEN_SALT: lksjdf1209jjjjaaaav_asd~a1
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: colonists
    links:
    - mongo
    restart: unless-stopped
    volumes:
    - .:/code

  app_client:
    build:
      context: .
      dockerfile: ./pkg/app/Dockerfile.dev
    command: yarn watch:client
    restart: unless-stopped
    volumes:
    - .:/code

  app_server:
    build:
      context: .
      dockerfile: ./pkg/app/Dockerfile.dev
    command: yarn watch:server
    depends_on:
    - babel
    environment:
      API_URL_SERVER: http://api:12950
      API_URL: http://localhost:12950
      APP_URL: http://localhost:12951
    links:
    - api
    restart: unless-stopped
    volumes:
    - .:/code

  babel:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn watch:scripts
    volumes:
    - .:/code

  caddy:
    image: joshix/caddy
    ports:
    - 12950:12950
    - 12951:12951
    volumes:
    - .:/var/www/html

  mongo:
    image: mongo:3.6.1-jessie
    volumes:
    - dbdata:/data/db

volumes:
  dbdata:
