version: '3'

services:
  api:
    build:
      context: ./pkg/api
      dockerfile: Dockerfile.dev
    command: yarn watch
    depends_on:
    - babel
    restart: unless-stopped
    volumes:
    - .:/code

  app_client:
    build:
      context: .
      dockerfile: ./pkg/app/Dockerfile.dev
    command: yarn watch:client
    restart: unless-stopped
    volumes:
    - .:/code

  app_server:
    build:
      context: .
      dockerfile: ./pkg/app/Dockerfile.dev
    command: yarn watch:server
    environment:
      API_URL: http://localhost:12950
    depends_on:
    - babel
    restart: unless-stopped
    volumes:
    - .:/code

  babel:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn watch:scripts
    volumes:
    - .:/code

  caddy:
    image: joshix/caddy
    ports:
    - 12950:12950
    - 12951:12951
    volumes:
    - .:/var/www/html
